//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank_Host.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string file_save_path {
            get {
                return ((string)(this["file_save_path"]));
            }
            set {
                this["file_save_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("K4")]
        public string LOCATION {
            get {
                return ((string)(this["LOCATION"]));
            }
            set {
                this["LOCATION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Loc_file_save_path {
            get {
                return ((string)(this["Loc_file_save_path"]));
            }
            set {
                this["Loc_file_save_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SPLIT_LOG_SAVE_PATH {
            get {
                return ((string)(this["SPLIT_LOG_SAVE_PATH"]));
            }
            set {
                this["SPLIT_LOG_SAVE_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SplitLogMailHead {
            get {
                return ((string)(this["SplitLogMailHead"]));
            }
            set {
                this["SplitLogMailHead"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SplitLogMailBody {
            get {
                return ((string)(this["SplitLogMailBody"]));
            }
            set {
                this["SplitLogMailBody"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SplitLogMailTail {
            get {
                return ((string)(this["SplitLogMailTail"]));
            }
            set {
                this["SplitLogMailTail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PrintOffsetX {
            get {
                return ((int)(this["PrintOffsetX"]));
            }
            set {
                this["PrintOffsetX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PrintOffsetY {
            get {
                return ((int)(this["PrintOffsetY"]));
            }
            set {
                this["PrintOffsetY"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.135.200.35;Initial Catalog=GR_Automation;Persist Security Info=Tru" +
            "e;User ID=amm")]
        public string GR_AutomationConnectionString {
            get {
                return ((string)(this["GR_AutomationConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SCRAP_DEFAULT_PATH {
            get {
                return ((string)(this["SCRAP_DEFAULT_PATH"]));
            }
            set {
                this["SCRAP_DEFAULT_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SCRAP_EXCEL_EXPORT_PATH {
            get {
                return ((string)(this["SCRAP_EXCEL_EXPORT_PATH"]));
            }
            set {
                this["SCRAP_EXCEL_EXPORT_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int TimeOutMin {
            get {
                return ((int)(this["TimeOutMin"]));
            }
            set {
                this["TimeOutMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string SecondPrinterIP {
            get {
                return ((string)(this["SecondPrinterIP"]));
            }
            set {
                this["SecondPrinterIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SecondPrinterCustName {
            get {
                return ((string)(this["SecondPrinterCustName"]));
            }
            set {
                this["SecondPrinterCustName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SecondPrinterOffsetX {
            get {
                return ((int)(this["SecondPrinterOffsetX"]));
            }
            set {
                this["SecondPrinterOffsetX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SecondPrinterOffsetY {
            get {
                return ((int)(this["SecondPrinterOffsetY"]));
            }
            set {
                this["SecondPrinterOffsetY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GreenLabelPrint {
            get {
                return ((bool)(this["GreenLabelPrint"]));
            }
            set {
                this["GreenLabelPrint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LabelCopy {
            get {
                return ((bool)(this["LabelCopy"]));
            }
            set {
                this["LabelCopy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WaferReturnExcelOutPath {
            get {
                return ((string)(this["WaferReturnExcelOutPath"]));
            }
            set {
                this["WaferReturnExcelOutPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WaferReturnCode {
            get {
                return ((string)(this["WaferReturnCode"]));
            }
            set {
                this["WaferReturnCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FontSize1 {
            get {
                return ((int)(this["FontSize1"]));
            }
            set {
                this["FontSize1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FontSize2 {
            get {
                return ((int)(this["FontSize2"]));
            }
            set {
                this["FontSize2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ReturnQualcomm {
            get {
                return ((bool)(this["ReturnQualcomm"]));
            }
            set {
                this["ReturnQualcomm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.0.100")]
        public string QualcommPrinterIP {
            get {
                return ((string)(this["QualcommPrinterIP"]));
            }
            set {
                this["QualcommPrinterIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string QualcommMSL {
            get {
                return ((string)(this["QualcommMSL"]));
            }
            set {
                this["QualcommMSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(e2)")]
        public string Qualcomm2nd {
            get {
                return ((string)(this["Qualcomm2nd"]));
            }
            set {
                this["Qualcomm2nd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string QorvoWSN {
            get {
                return ((string)(this["QorvoWSN"]));
            }
            set {
                this["QorvoWSN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KEYENCE")]
        public string CameraType {
            get {
                return ((string)(this["CameraType"]));
            }
            set {
                this["CameraType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.100.2;192.168.100.2")]
        public string ReaderIP {
            get {
                return ((string)(this["ReaderIP"]));
            }
            set {
                this["ReaderIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9004;23")]
        public string ReaderPort {
            get {
                return ((string)(this["ReaderPort"]));
            }
            set {
                this["ReaderPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FALSE;TRUE")]
        public string ReaderWebpage {
            get {
                return ((string)(this["ReaderWebpage"]));
            }
            set {
                this["ReaderWebpage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int CognexTriggerCnt {
            get {
                return ((int)(this["CognexTriggerCnt"]));
            }
            set {
                this["CognexTriggerCnt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int SplitWLabel {
            get {
                return ((int)(this["SplitWLabel"]));
            }
            set {
                this["SplitWLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("diebank")]
        public string USER_NAME {
            get {
                return ((string)(this["USER_NAME"]));
            }
            set {
                this["USER_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("diebank@123")]
        public string USER_PW {
            get {
                return ((string)(this["USER_PW"]));
            }
            set {
                this["USER_PW"] = value;
            }
        }
    }
}
